version: '3.8'

services:
  cli:
    build:
      context: docker
      dockerfile: dev/php-cli/Dockerfile
    volumes:
      - ./app:/app
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  postgresql:
    image: postgres:16-alpine3.18
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
      - ./app:/app
    ports:
      - "5432:5432"
    working_dir: /app

